import { useEffect, useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";
import "../styles/ReportCard.css";

export default function ReportCard() {
  const navigate = useNavigate();
  const reportRef = useRef();
  const userId=localStorage.getItem("user_id");
  const [data, setData] = useState({
    name: "Student",
    email: "",
    college: "",
    department: "",
    total_quizzes: 0,
    average_score: 0,
    strong_topics: [],
    weak_topics: [],
    ai_insight: "",
    last_taken: null
  });

  // ---------------- FETCH ----------------
  useEffect(() => {
    if (!userId) return;
    fetch(`http://localhost:8000/report/${userId}`)
      .then(res => res.json())
      .then(setData)
      .catch(console.error);
  }, []);

  const {
    name,
    email,
    college,
    department,
    total_quizzes,
    average_score,
    strong_topics = [],
    weak_topics = [],
    ai_insight,
    last_taken
  } = data;

  // ---------------- SAFE LEVEL ----------------
  const getLevel = (score = 0) => {
    if (score >= 80) return "Advanced";
    if (score >= 60) return "Intermediate";
    if (score >= 40) return "Beginner";
    return "Needs Improvement";
  };

  // ---------------- FIX DATE ----------------
  const formattedDate = last_taken
    ? new Date(last_taken).toLocaleString()
    : "N/A";

  // ---------------- PDF EXPORT ----------------
  const downloadPDF = async () => {
    const element = reportRef.current;

    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true
    });

    const imgData = canvas.toDataURL("image/png");

    const pdf = new jsPDF("p", "mm", "a4");
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
    pdf.save(`${name}_report_card.pdf`);
  };

  return (
    <div className="report-wrapper">

      {/* ACTION BAR */}
      <div className="report-actions">
        <button onClick={() => navigate("/home")}>Home</button>
        <button onClick={downloadPDF} className="primary">
          Download PDF
        </button>
      </div>

      {/* PDF CONTENT */}
      <div ref={reportRef} className="report-paper">

        <h1>📘 Academic Report Card</h1>
        <p>{college || "College"} • {department || "Department"}</p>

        <hr />

        {/* STUDENT INFO */}
        <div className="section">
          <h2>Student Info</h2>
          <p><b>Name:</b> {name}</p>
          <p><b>Email:</b> {email || "N/A"}</p>
          <p><b>Last Taken:</b> {formattedDate}</p>
        </div>

        {/* PERFORMANCE */}
        <div className="section">
          <h2>Performance</h2>
          <h3>Score: {average_score?.toFixed?.(1) || 0}%</h3>
          <h3>Level: {getLevel(average_score)}</h3>
          <h3>Total Quizzes: {total_quizzes}</h3>
        </div>

        {/* AI INSIGHT */}
        <div className="section">
          <h2>AI Insight</h2>
          <p>{ai_insight || "Performance improving with practice."}</p>
        </div>

        {/* STRONG */}
        <div className="section">
          <h2>Strong Areas</h2>
          {strong_topics.length > 0 ? (
            <ul>
              {strong_topics.map((t, i) => (
                <li key={i}>{t}</li>
              ))}
            </ul>
          ) : (
            <p>No strong topics yet.</p>
          )}
        </div>

        {/* WEAK */}
        <div className="section">
          <h2>Weak Areas</h2>
          {weak_topics.length > 0 ? (
            <ul>
              {weak_topics.map((t, i) => (
                <li key={i}>{t}</li>
              ))}
            </ul>
          ) : (
            <p>No weak topics 🎉</p>
          )}
        </div>

        {/* FOOTER */}
        <div className="footer">
          Generated by AI Study Companion
        </div>

      </div>
    </div>
  );
}